apiVersion: v1
kind: Namespace
metadata:
  name: core-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core-api
  name: core-api
  namespace: core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - image: cssonddos/core-api:1.0.3
        name: core-api
        imagePullPolicy: Always
        env:
        - name: endpoint
          value: "redis-cluster.redis.svc.cluster.local"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: core-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: core-api
  type: ClusterIP